---
- name: Install container tools
  hosts: servers
  tasks:
    - name: Install podman, buildah and skopeo
      dnf:
        name: 
          - podman
          - podman-docker
          - buildah
          - skopeo
- name: Pull images to unprivileged account
  hosts: servers
  become: false
  tasks:
    - podman_image:
        name: registry.fedoraproject.org/fedora-minimal
        tag: 30
    - podman_image:
        name: registry.fedoraproject.org/fedora
        tag: 30

